AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Max: 160
